// Quiz datasets for Spanish learning with Armenian translations

export interface MultipleChoiceQuestion {
  id: number;
  letter?: string;
  spanish: string;
  armenian: string;
  options: { key: 'a' | 'b' | 'c' | 'd'; text: string }[];
  correct: 'a' | 'b' | 'c' | 'd';
  explanationEs: string;
  explanationHy: string;
  prize?: string;
}

export interface NumberQuestion {
  id: number;
  letter: string;
  numStr: string;
  numberValue: number;
  spanishText: string;
  armenianText: string;
  wordInSpanish: string;
  wrongOptions: string[];
}

export interface MathProblem {
  id: number;
  spanish: string;
  armenian: string;
  result: number;
  unitEs: string;
  unitHy: string;
  operation: string;
  explanationEs: string;
  explanationHy: string;
}

// 1. MILLONARIO: 15 preguntas (ser / estar / tener / tener que + clima)
export const MILLONARIO_QUESTIONS: MultipleChoiceQuestion[] = [
  {
    id: 1,
    prize: "100 €",
    spanish: "Hoy ___ mucho frío.",
    armenian: "Այսօր շատ ցուրտ է։",
    options: [
      { key: "a", text: "es" },
      { key: "b", text: "está" },
      { key: "c", text: "hace" },
      { key: "d", text: "tiene" },
    ],
    correct: "c",
    explanationEs: "Para el clima y la temperatura usamos el verbo 'hacer': hace frío, hace calor, hace viento.",
    explanationHy: "Եղանակի և ջերմաստիճանի համար օգտագործվում է 'hacer' բայը (hace frío - ցուրտ է):",
  },
  {
    id: 2,
    prize: "200 €",
    spanish: "Marta ___ cansada hoy.",
    armenian: "Մարտան այսօր հոգնած է։",
    options: [
      { key: "a", text: "es" },
      { key: "b", text: "está" },
      { key: "c", text: "tiene" },
      { key: "d", text: "hace" },
    ],
    correct: "b",
    explanationEs: "Usamos 'estar' para estados temporales físicos o de ánimo: está cansada.",
    explanationHy: "Ժամանակավոր ֆիզիկական կամ հուզական վիճակի համար օգտագործվում է 'estar' (está cansada):",
  },
  {
    id: 3,
    prize: "300 €",
    spanish: "Nosotros ___ dos clases hoy.",
    armenian: "Մենք այսօր երկու դաս ունենք։",
    options: [
      { key: "a", text: "somos" },
      { key: "b", text: "estamos" },
      { key: "c", text: "tenemos" },
      { key: "d", text: "hacemos" },
    ],
    correct: "c",
    explanationEs: "Para posesión o compromisos programados usamos 'tener': nosotros tenemos.",
    explanationHy: "Ունենալու կամ պլանավորված դասերի համար օգտագործվում է 'tener' (tenemos):",
  },
  {
    id: 4,
    prize: "500 €",
    spanish: "Pedro ___ estudiar esta tarde.",
    armenian: "Պեդրոն պետք է սովորի այսօր կեսօրից հետո։",
    options: [
      { key: "a", text: "tiene" },
      { key: "b", text: "está" },
      { key: "c", text: "tiene que" },
      { key: "d", text: "es" },
    ],
    correct: "c",
    explanationEs: "La perífrasis de obligación es 'tener que + infinitivo': tiene que estudiar.",
    explanationHy: "Պարտադրանք կամ անհրաժեշտություն արտահայտելու համար՝ 'tener que + անորոշ դերբայ' (tiene que estudiar):",
  },
  {
    id: 5,
    prize: "1.000 €",
    spanish: "Barcelona ___ una ciudad muy bonita.",
    armenian: "Բարսելոնան շատ գեղեցիկ քաղաք է։",
    options: [
      { key: "a", text: "está" },
      { key: "b", text: "es" },
      { key: "c", text: "tiene" },
      { key: "d", text: "hace" },
    ],
    correct: "b",
    explanationEs: "Para características esenciales y definiciones usamos 'ser': Barcelona es una ciudad bonita.",
    explanationHy: "Էական հատկանիշների և սահմանումների համար օգտագործվում է 'ser' (es una ciudad):",
  },
  {
    id: 6,
    prize: "2.000 €",
    spanish: "Hoy el cielo ___ nublado.",
    armenian: "Այսօր երկինքը ամպամած է։",
    options: [
      { key: "a", text: "es" },
      { key: "b", text: "está" },
      { key: "c", text: "tiene" },
      { key: "d", text: "hace" },
    ],
    correct: "b",
    explanationEs: "El estado actual del cielo es temporal, por lo que usamos 'estar': está nublado / despejado.",
    explanationHy: "Երկնքի ներկա ժամանակավոր վիճակի համար օգտագործվում է 'estar' (está nublado):",
  },
  {
    id: 7,
    prize: "4.000 €",
    spanish: "Yo ___ hambre.",
    armenian: "Ես քաղցած եմ։",
    options: [
      { key: "a", text: "soy" },
      { key: "b", text: "estoy" },
      { key: "c", text: "tengo" },
      { key: "d", text: "hago" },
    ],
    correct: "c",
    explanationEs: "En español las sensaciones fisiológicas van con 'tener': tener hambre, tener sed, tener sueño.",
    explanationHy: "Իսպաներենում ֆիզիոլոգիական զգացողությունները արտահայտվում են 'tener'-ով (tengo hambre):",
  },
  {
    id: 8,
    prize: "8.000 €",
    spanish: "Mañana nosotros ___ trabajar temprano.",
    armenian: "Վաղը մենք պետք է շուտ աշխատենք։",
    options: [
      { key: "a", text: "somos" },
      { key: "b", text: "tenemos que" },
      { key: "c", text: "estamos" },
      { key: "d", text: "tenemos" },
    ],
    correct: "b",
    explanationEs: "Obligación personal en primera persona del plural: tenemos que trabajar.",
    explanationHy: "Պարտավորություն հոգնակի 1-ին դեմքում՝ tenemos que trabajar (մենք պետք է աշխատենք):",
  },
  {
    id: 9,
    prize: "16.000 €",
    spanish: "Mi hermano ___ médico.",
    armenian: "Իմ եղբայրը բժիշկ է։",
    options: [
      { key: "a", text: "está" },
      { key: "b", text: "es" },
      { key: "c", text: "tiene" },
      { key: "d", text: "hace" },
    ],
    correct: "b",
    explanationEs: "Para profesiones e identidades se usa siempre el verbo 'ser': es médico.",
    explanationHy: "Մասնագիտությունների և ինքնության համար միշտ օգտագործվում է 'ser' (es médico):",
  },
  {
    id: 10,
    prize: "32.000 €",
    spanish: "Hoy ___ mucho viento.",
    armenian: "Այսօր ուժեղ քամի է։",
    options: [
      { key: "a", text: "está" },
      { key: "b", text: "tiene" },
      { key: "c", text: "hace" },
      { key: "d", text: "es" },
    ],
    correct: "c",
    explanationEs: "Fenómenos meteorológicos atmosféricos: hace viento, hace sol, hace frío.",
    explanationHy: "Մթնոլորտային երևույթների համար օգտագործվում է 'hace' (hace viento - քամի է փչում):",
  },
  {
    id: 11,
    prize: "64.000 €",
    spanish: "Los niños ___ en casa ahora.",
    armenian: "Երեխաները հիմա տանն են։",
    options: [
      { key: "a", text: "son" },
      { key: "b", text: "están" },
      { key: "c", text: "tienen" },
      { key: "d", text: "hacen" },
    ],
    correct: "b",
    explanationEs: "Para localización o ubicación espacial se usa siempre 'estar': están en casa.",
    explanationHy: "Գտնվելու վայրի համար միշտ օգտագործվում է 'estar' (están en casa - տանն են):",
  },
  {
    id: 12,
    prize: "125.000 €",
    spanish: "Ana ___ 25 años.",
    armenian: "Անան 25 տարեկան է։",
    options: [
      { key: "a", text: "es" },
      { key: "b", text: "está" },
      { key: "c", text: "tiene" },
      { key: "d", text: "hace" },
    ],
    correct: "c",
    explanationEs: "La edad en español se expresa con 'tener': tener ... años (Ana tiene 25 años).",
    explanationHy: "Տարիքը իսպաներենում արտահայտվում է 'tener' բայով (tiene 25 años):",
  },
  {
    id: 13,
    prize: "250.000 €",
    spanish: "Tú ___ beber más agua.",
    armenian: "Դու պետք է ավելի շատ ջուր խմես։",
    options: [
      { key: "a", text: "tienes que" },
      { key: "b", text: "eres" },
      { key: "c", text: "estás" },
      { key: "d", text: "tienes" },
    ],
    correct: "a",
    explanationEs: "Recomendación u obligación directa: 'tienes que + infinitivo'.",
    explanationHy: "Առաջադրանք կամ խորհուրդ դու-ի համար՝ tienes que beber (պետք է խմես):",
  },
  {
    id: 14,
    prize: "500.000 €",
    spanish: "En verano normalmente ___ calor.",
    armenian: "Ամռանը սովորաբար շոգ է։",
    options: [
      { key: "a", text: "está" },
      { key: "b", text: "es" },
      { key: "c", text: "hace" },
      { key: "d", text: "tiene" },
    ],
    correct: "c",
    explanationEs: "Para la temperatura del ambiente usamos 'hace': hace calor.",
    explanationHy: "Շրջակա միջավայրի ջերմաստիճանի համար օգտագործվում է 'hace calor' (շոգ է):",
  },
  {
    id: 15,
    prize: "1.000.000 €",
    spanish: "Mis amigos ___ muy simpáticos.",
    armenian: "Իմ ընկերները շատ հաճելի մարդիկ են։",
    options: [
      { key: "a", text: "están" },
      { key: "b", text: "tienen" },
      { key: "c", text: "son" },
      { key: "d", text: "hacen" },
    ],
    correct: "c",
    explanationEs: "Para rasgos de personalidad y carácter duraderos usamos 'ser': son simpáticos.",
    explanationHy: "Բնավորության կայուն գծերի համար օգտագործվում է 'ser' (son simpáticos):",
  },
];

// Pasapalabra letters (27 letters matching Spanish alphabet)
export const ROSCO_LETTERS = [
  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
  'N', 'Ñ', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'
];

// 2. PASAPALABRA VERBOS: 27 preguntas (saber / conocer / oír / escuchar / gustar / llevar / traer)
export const VERBOS_QUESTIONS: MultipleChoiceQuestion[] = [
  {
    id: 1,
    letter: "A",
    spanish: "Yo no ___ dónde vive Carlos.",
    armenian: "Ես չգիտեմ, թե որտեղ է ապրում Կառլոսը։",
    options: [
      { key: "a", text: "conozco" },
      { key: "b", text: "sé" },
      { key: "c", text: "escucho" },
      { key: "d", text: "llevo" },
    ],
    correct: "b",
    explanationEs: "'Saber' se usa para información, hechos y datos (dónde vive). Forma yo: 'sé'.",
    explanationHy: "'Saber'-ը օգտագործվում է փաստերի և տեղեկությունների համար (չգիտեմ՝ որտեղ է ապրում):",
  },
  {
    id: 2,
    letter: "B",
    spanish: "¿___ tú a María?",
    armenian: "Դու ճանաչո՞ւմ ես Մարիային։",
    options: [
      { key: "a", text: "Sabes" },
      { key: "b", text: "Conoces" },
      { key: "c", text: "Oyes" },
      { key: "d", text: "Traes" },
    ],
    correct: "b",
    explanationEs: "'Conocer' se usa para personas y lugares (+ 'a' personal): ¿Conoces a María?",
    explanationHy: "Մարդկանց և վայրերին ճանաչելու համար օգտագործվում է 'conocer' (conoces a María):",
  },
  {
    id: 3,
    letter: "C",
    spanish: "No te ___ bien, habla más alto.",
    armenian: "Ես քեզ լավ չեմ լսում, ավելի բարձր խոսիր։",
    options: [
      { key: "a", text: "escucho" },
      { key: "b", text: "oigo" },
      { key: "c", text: "conozco" },
      { key: "d", text: "sé" },
    ],
    correct: "b",
    explanationEs: "'Oír' es la percepción física involuntaria del sonido. Forma yo: 'oigo'.",
    explanationHy: "'Oír'-ը ֆիզիկապես ձայնը լսելն է (չեմ լսում ձայնդ՝ oigo):",
  },
  {
    id: 4,
    letter: "D",
    spanish: "Me gusta ___ música cuando trabajo.",
    armenian: "Ես սիրում եմ երաժշտություն լսել, երբ աշխատում եմ։",
    options: [
      { key: "a", text: "oír" },
      { key: "b", text: "escuchar" },
      { key: "c", text: "conocer" },
      { key: "d", text: "traer" },
    ],
    correct: "b",
    explanationEs: "'Escuchar' implica prestar atención voluntaria: escuchar música.",
    explanationHy: "'Escuchar' նշանակում է ուշադիր, գիտակցաբար լսել (երաժշտություն լսել):",
  },
  {
    id: 5,
    letter: "E",
    spanish: "A Ana le ___ mucho el chocolate.",
    armenian: "Անան շատ է սիրում շոկոլադ։",
    options: [
      { key: "a", text: "gusta" },
      { key: "b", text: "gustan" },
      { key: "c", text: "sabe" },
      { key: "d", text: "lleva" },
    ],
    correct: "a",
    explanationEs: "'El chocolate' es singular, por lo tanto el verbo 'gustar' va en singular: 'le gusta'.",
    explanationHy: "'El chocolate'-ը եզակի է, հետևաբար բայը եզակի է՝ 'gusta':",
  },
  {
    id: 6,
    letter: "F",
    spanish: "Pedro ___ una mochila negra.",
    armenian: "Պեդրոն սև ուսապարկ է կրում։",
    options: [
      { key: "a", text: "trae" },
      { key: "b", text: "lleva" },
      { key: "c", text: "oye" },
      { key: "d", text: "conoce" },
    ],
    correct: "b",
    explanationEs: "'Llevar' se usa para prendas, accesorios o transportar cosas hacia allá: lleva una mochila.",
    explanationHy: "Հագուստ կամ ուսապարկ կրելու համար օգտագործվում է 'llevar':",
  },
  {
    id: 7,
    letter: "G",
    spanish: "¿Puedes ___ el libro mañana?",
    armenian: "Կարո՞ղ ես վաղը գիրքը բերել։",
    options: [
      { key: "a", text: "llevar" },
      { key: "b", text: "traer" },
      { key: "c", text: "saber" },
      { key: "d", text: "escuchar" },
    ],
    correct: "b",
    explanationEs: "'Traer' es mover algo hacia el lugar donde está la persona que habla (aquí): traer el libro.",
    explanationHy: "'Traer' նշանակում է բերել դեպի խոսողը (այստեղ բերել):",
  },
  {
    id: 8,
    letter: "H",
    spanish: "¿___ cocinar paella?",
    armenian: "Դու գիտե՞ս պաեյա պատրաստել։",
    options: [
      { key: "a", text: "Conoces" },
      { key: "b", text: "Sabes" },
      { key: "c", text: "Oyes" },
      { key: "d", text: "Gustas" },
    ],
    correct: "b",
    explanationEs: "'Saber + infinitivo' expresa habilidad o saber hacer algo: ¿Sabes cocinar?",
    explanationHy: "'Saber + infinitivo' նշանակում է կարողանալ, իմանալ ինչ-որ բան անել:",
  },
  {
    id: 9,
    letter: "I",
    spanish: "Nosotros ___ muy bien Barcelona.",
    armenian: "Մենք շատ լավ ճանաչում ենք Բարսելոնան։",
    options: [
      { key: "a", text: "sabemos" },
      { key: "b", text: "conocemos" },
      { key: "c", text: "escuchamos" },
      { key: "d", text: "traemos" },
    ],
    correct: "b",
    explanationEs: "Para ciudades y lugares familiares usamos 'conocer': conocemos Barcelona.",
    explanationHy: "Քաղաքներ և վայրեր ճանաչելու/այցելած լինելու համար՝ 'conocer' (conocemos Barcelona):",
  },
  {
    id: 10,
    letter: "J",
    spanish: "Desde aquí se ___ el ruido de los coches.",
    armenian: "Այստեղից լսվում է մեքենաների աղմուկը։",
    options: [
      { key: "a", text: "escucha" },
      { key: "b", text: "oye" },
      { key: "c", text: "sabe" },
      { key: "d", text: "conoce" },
    ],
    correct: "b",
    explanationEs: "Percepción involuntaria de sonido pasivo: 'se oye el ruido'.",
    explanationHy: "Աղմուկը լսվում է (ակամա ֆիզիկական լսողություն)՝ se oye el ruido:",
  },
  {
    id: 11,
    letter: "K",
    spanish: "Siempre ___ las explicaciones del profesor con atención.",
    armenian: "Ես միշտ ուշադիր լսում եմ ուսուցչի բացատրությունները։",
    options: [
      { key: "a", text: "oigo" },
      { key: "b", text: "escucho" },
      { key: "c", text: "sé" },
      { key: "d", text: "llevo" },
    ],
    correct: "b",
    explanationEs: "'Con atención' exige el verbo de escucha activa: escucho.",
    explanationHy: "'Ուշադրությամբ' բառը պահանջում է 'escucho' (ուշադիր լսում եմ):",
  },
  {
    id: 12,
    letter: "L",
    spanish: "A mis padres les ___ viajar.",
    armenian: "Իմ ծնողները սիրում են ճանապարհորդել։",
    options: [
      { key: "a", text: "gusta" },
      { key: "b", text: "gustan" },
      { key: "c", text: "conocen" },
      { key: "d", text: "oyen" },
    ],
    correct: "a",
    explanationEs: "Cuando el sujeto es un verbo en infinitivo ('viajar'), 'gustar' siempre es singular: 'gusta'.",
    explanationHy: "Երբ դրված է անորոշ դերբայ (viajar), 'gustar'-ը միշտ եզակի է՝ 'les gusta':",
  },
  {
    id: 13,
    letter: "M",
    spanish: "Lucía ___ gafas hoy.",
    armenian: "Լուսիան այսօր ակնոց է կրում։",
    options: [
      { key: "a", text: "trae" },
      { key: "b", text: "lleva" },
      { key: "c", text: "sabe" },
      { key: "d", text: "oye" },
    ],
    correct: "b",
    explanationEs: "Para llevar puesto ropa o accesorios: Lucía lleva gafas.",
    explanationHy: "Ակնոց կամ հագուստ կրելու համար՝ 'lleva gafas':",
  },
  {
    id: 14,
    letter: "N",
    spanish: "Yo ___ comida para la fiesta.",
    armenian: "Ես ուտելիք եմ բերում երեկույթի համար։",
    options: [
      { key: "a", text: "llevo" },
      { key: "b", text: "traigo" },
      { key: "c", text: "conozco" },
      { key: "d", text: "escucho" },
    ],
    correct: "b",
    explanationEs: "Primera persona de traer: 'yo traigo' (traer aquí a la fiesta).",
    explanationHy: "'Traer' բայի 1-ին դեմքը՝ 'traigo' (բերում եմ):",
  },
  {
    id: 15,
    letter: "Ñ",
    spanish: "¿___ la respuesta?",
    armenian: "Գիտե՞ս պատասխանը։",
    options: [
      { key: "a", text: "Conoces" },
      { key: "b", text: "Sabes" },
      { key: "c", text: "Oyes" },
      { key: "d", text: "Llevas" },
    ],
    correct: "b",
    explanationEs: "Para respuestas, soluciones y datos se usa 'saber': ¿Sabes la respuesta?",
    explanationHy: "Պատասխանը իմանալու համար՝ 'sabes' (գիտե՞ս պատասխանը):",
  },
  {
    id: 16,
    letter: "O",
    spanish: "¿___ este restaurante?",
    armenian: "Դու ճանաչո՞ւմ ես այս ռեստորանը։",
    options: [
      { key: "a", text: "Sabes" },
      { key: "b", text: "Conoces" },
      { key: "c", text: "Escuchas" },
      { key: "d", text: "Traes" },
    ],
    correct: "b",
    explanationEs: "Para establecimientos y lugares que uno ha visitado se usa 'conocer': ¿Conoces este restaurante?",
    explanationHy: "Ռեստորանը կամ վայրը ճանաչելու համար՝ 'conoces':",
  },
  {
    id: 17,
    letter: "P",
    spanish: "No ___ nada porque hay mucho ruido.",
    armenian: "Ես ոչինչ չեմ լսում, որովհետև շատ աղմուկ կա։",
    options: [
      { key: "a", text: "escucho" },
      { key: "b", text: "oigo" },
      { key: "c", text: "conozco" },
      { key: "d", text: "llevo" },
    ],
    correct: "b",
    explanationEs: "Imposibilidad de percepción sonora física por ruido: no oigo nada.",
    explanationHy: "Աղմուկի պատճառով ֆիզիկապես ոչինչ չլսել՝ 'no oigo nada':",
  },
  {
    id: 18,
    letter: "Q",
    spanish: "Por favor, ___ lo que te digo.",
    armenian: "Խնդրում եմ, լսիր այն, ինչ ասում եմ քեզ։",
    options: [
      { key: "a", text: "oye" },
      { key: "b", text: "escucha" },
      { key: "c", text: "conoce" },
      { key: "d", text: "sabe" },
    ],
    correct: "b",
    explanationEs: "Imperativo de prestar atención: 'escucha lo que te digo'.",
    explanationHy: "Ուշադրություն պահանջող հրամայական եղանակ՝ 'escucha' (լսիր):",
  },
  {
    id: 19,
    letter: "R",
    spanish: "A Carlos le ___ los perros.",
    armenian: "Կառլոսը սիրում է շներին։",
    options: [
      { key: "a", text: "gusta" },
      { key: "b", text: "gustan" },
      { key: "c", text: "lleva" },
      { key: "d", text: "trae" },
    ],
    correct: "b",
    explanationEs: "El sujeto es 'los perros' (plural), por eso el verbo concuerda en plural: 'le gustan'.",
    explanationHy: "Ենթական հոգնակի է (los perros), հետևաբար՝ 'gustan':",
  },
  {
    id: 20,
    letter: "S",
    spanish: "María ___ un vestido rojo.",
    armenian: "Մարիան կարմիր զգեստ է կրում։",
    options: [
      { key: "a", text: "trae" },
      { key: "b", text: "lleva" },
      { key: "c", text: "escucha" },
      { key: "d", text: "sabe" },
    ],
    correct: "b",
    explanationEs: "Llevar ropa puesta: María lleva un vestido rojo.",
    explanationHy: "Հագուստ կրելու համար՝ 'lleva un vestido rojo':",
  },
  {
    id: 21,
    letter: "T",
    spanish: "¿Puedes ___ estas cajas a la cocina?",
    armenian: "Կարո՞ղ ես այս տուփերը տանել խոհանոց։",
    options: [
      { key: "a", text: "traer" },
      { key: "b", text: "llevar" },
      { key: "c", text: "conocer" },
      { key: "d", text: "oír" },
    ],
    correct: "b",
    explanationEs: "'Llevar' es transportar desde aquí hacia allá (hacia la cocina).",
    explanationHy: "'Llevar' նշանակում է տանել այստեղից դեպի այլ վայր (տանել խոհանոց):",
  },
  {
    id: 22,
    letter: "U",
    spanish: "Cuando vengas, ___ agua, por favor.",
    armenian: "Երբ գաս, խնդրում եմ ջուր բեր։",
    options: [
      { key: "a", text: "lleva" },
      { key: "b", text: "trae" },
      { key: "c", text: "escucha" },
      { key: "d", text: "conoce" },
    ],
    correct: "b",
    explanationEs: "Imperativo de traer hacia donde yo estoy: 'trae agua'.",
    explanationHy: "Դեպի ինձ բերելու հրամայականը՝ 'trae' (ջուր բեր):",
  },
  {
    id: 23,
    letter: "V",
    spanish: "No ___ hablar italiano.",
    armenian: "Ես իտալերեն խոսել չգիտեմ։",
    options: [
      { key: "a", text: "conozco" },
      { key: "b", text: "sé" },
      { key: "c", text: "oigo" },
      { key: "d", text: "gusto" },
    ],
    correct: "b",
    explanationEs: "Saber idiomas o habilidades: 'no sé hablar italiano'.",
    explanationHy: "Լեզվին տիրապետել կամ կարողանալ՝ 'sé' (չգիտեմ խոսել՝ no sé hablar):",
  },
  {
    id: 24,
    letter: "W",
    spanish: "¿___ a algún profesor español?",
    armenian: "Դու ճանաչո՞ւմ ես որևէ իսպանացի ուսուցչի։",
    options: [
      { key: "a", text: "Sabes" },
      { key: "b", text: "Conoces" },
      { key: "c", text: "Escuchas" },
      { key: "d", text: "Llevas" },
    ],
    correct: "b",
    explanationEs: "Conocer a personas: ¿Conoces a algún profesor?",
    explanationHy: "Մարդկանց ճանաչելու համար օգտագործվում է 'conocer' (conoces):",
  },
  {
    id: 25,
    letter: "X",
    spanish: "¿___ ese sonido?",
    armenian: "Լսո՞ւմ ես այդ ձայնը։",
    options: [
      { key: "a", text: "Conoces" },
      { key: "b", text: "Oyes" },
      { key: "c", text: "Sabes" },
      { key: "d", text: "Traes" },
    ],
    correct: "b",
    explanationEs: "Percepción de un sonido puntual: ¿Oyes ese sonido?",
    explanationHy: "Հնչյունը ֆիզիկապես լսելու համար՝ 'oyes' (լսո՞ւմ ես այդ ձայնը):",
  },
  {
    id: 26,
    letter: "Y",
    spanish: "Me gusta ___ podcasts en español.",
    armenian: "Ես սիրում եմ իսպաներեն փոդքասթեր լսել։",
    options: [
      { key: "a", text: "oír" },
      { key: "b", text: "escuchar" },
      { key: "c", text: "llevar" },
      { key: "d", text: "conocer" },
    ],
    correct: "b",
    explanationEs: "Consumir contenidos de audio con atención: 'escuchar podcasts'.",
    explanationHy: "Աուդիո բովանդակություն ուշադիր լսելու համար՝ 'escuchar podcasts':",
  },
  {
    id: 27,
    letter: "Z",
    spanish: "A nosotros nos ___ mucho estas canciones.",
    armenian: "Մենք շատ ենք սիրում այս երգերը։",
    options: [
      { key: "a", text: "gusta" },
      { key: "b", text: "gustan" },
      { key: "c", text: "sabemos" },
      { key: "d", text: "traemos" },
    ],
    correct: "b",
    explanationEs: "'Estas canciones' es plural, por lo que el verbo concuerda en plural: 'nos gustan'.",
    explanationHy: "'Estas canciones'-ը հոգնակի է, հետևաբար՝ 'nos gustan':",
  },
];

// 3. PASAPALABRA NÚMEROS: 27 preguntas
export const NUMEROS_QUESTIONS: NumberQuestion[] = [
  {
    id: 1,
    letter: "A",
    numStr: "347",
    numberValue: 347,
    spanishText: "¿Cómo se dice 347 en español?",
    armenianText: "Ինչպե՞ս է 347-ը իսպաներեն։",
    wordInSpanish: "trescientos cuarenta y siete",
    wrongOptions: ["tres cientos cuarenta siete", "trescientos cuatro y siete", "trescientos sesenta y siete"]
  },
  {
    id: 2,
    letter: "B",
    numStr: "918",
    numberValue: 918,
    spanishText: "¿Cómo se dice 918 en español?",
    armenianText: "Ինչպե՞ս է 918-ը իսպաներեն։",
    wordInSpanish: "novecientos dieciocho",
    wrongOptions: ["nuevecientos dieciocho", "novecientos diez y ocho", "ochocientos dieciocho"]
  },
  {
    id: 3,
    letter: "C",
    numStr: "1 264",
    numberValue: 1264,
    spanishText: "¿Cómo se dice 1 264 en español?",
    armenianText: "Ինչպե՞ս է 1 264-ը իսպաներեն։",
    wordInSpanish: "mil doscientos sesenta y cuatro",
    wrongOptions: ["un mil doscientos sesenta y cuatro", "mil doscientos setenta y cuatro", "mil doscientos sesenta cuatro"]
  },
  {
    id: 4,
    letter: "D",
    numStr: "2 075",
    numberValue: 2075,
    spanishText: "¿Cómo se dice 2 075 en español?",
    armenianText: "Ինչպե՞ս է 2 075-ը իսպաներեն։",
    wordInSpanish: "dos mil setenta y cinco",
    wrongOptions: ["dos mil setecientos cinco", "dos mil sesenta y cinco", "dos mil y setenta y cinco"]
  },
  {
    id: 5,
    letter: "E",
    numStr: "3 490",
    numberValue: 3490,
    spanishText: "¿Cómo se dice 3 490 en español?",
    armenianText: "Ինչպե՞ս է 3 490-ը իսպաներեն։",
    wordInSpanish: "tres mil cuatrocientos noventa",
    wrongOptions: ["tres mil cuatrocientos noventa y nueve", "tres mil cuatrocientos ochenta", "tres mil cuatros noventa"]
  },
  {
    id: 6,
    letter: "F",
    numStr: "4 812",
    numberValue: 4812,
    spanishText: "¿Cómo se dice 4 812 en español?",
    armenianText: "Ինչպե՞ս է 4 812-ը իսպաներեն։",
    wordInSpanish: "cuatro mil ochocientos doce",
    wrongOptions: ["cuatro mil ochocientos diez y dos", "cuatro mil setecientos doce", "cuatro mil ochocientos dos"]
  },
  {
    id: 7,
    letter: "G",
    numStr: "5 603",
    numberValue: 5603,
    spanishText: "¿Cómo se dice 5 603 en español?",
    armenianText: "Ինչպե՞ս է 5 603-ը իսպաներեն։",
    wordInSpanish: "cinco mil seiscientos tres",
    wrongOptions: ["cinco mil seiscientos treinta", "cinco mil seis cientos tres", "cinco mil setecientos tres"]
  },
  {
    id: 8,
    letter: "H",
    numStr: "6 975",
    numberValue: 6975,
    spanishText: "¿Cómo se dice 6 975 en español?",
    armenianText: "Ինչպե՞ս է 6 975-ը իսպաներեն։",
    wordInSpanish: "seis mil novecientos setenta y cinco",
    wrongOptions: ["seis mil nuevecientos setenta y cinco", "seis mil novecientos sesenta y cinco", "seis mil novecientos setenta cinco"]
  },
  {
    id: 9,
    letter: "I",
    numStr: "7 245",
    numberValue: 7245,
    spanishText: "¿Cómo se dice 7 245 en español?",
    armenianText: "Ինչպե՞ս է 7 245-ը իսպաներեն։",
    wordInSpanish: "siete mil doscientos cuarenta y cinco",
    wrongOptions: ["siete mil doscientos cincuenta y cuatro", "siete mil doscientos cuarenta cinco", "siete mil trescientos cuarenta y cinco"]
  },
  {
    id: 10,
    letter: "J",
    numStr: "8 330",
    numberValue: 8330,
    spanishText: "¿Cómo se dice 8 330 en español?",
    armenianText: "Ինչպե՞ս է 8 330-ը իսպաներեն։",
    wordInSpanish: "ocho mil trescientos treinta",
    wrongOptions: ["ocho mil trescientos tres", "ocho mil trescientos trece", "ocho mil cuatrocientos treinta"]
  },
  {
    id: 11,
    letter: "K",
    numStr: "9 764",
    numberValue: 9764,
    spanishText: "¿Cómo se dice 9 764 en español?",
    armenianText: "Ինչպե՞ս է 9 764-ը իսպաներեն։",
    wordInSpanish: "nueve mil setecientos sesenta y cuatro",
    wrongOptions: ["nueve mil sietecientos sesenta y cuatro", "nueve mil setecientos setenta y cuatro", "ocho mil setecientos sesenta y cuatro"]
  },
  {
    id: 12,
    letter: "L",
    numStr: "1 508",
    numberValue: 1508,
    spanishText: "¿Cómo se dice 1 508 en español?",
    armenianText: "Ինչպե՞ս է 1 508-ը իսպաներեն։",
    wordInSpanish: "mil quinientos ocho",
    wrongOptions: ["mil cincocientos ocho", "un mil quinientos ocho", "mil quinientos ochenta"]
  },
  {
    id: 13,
    letter: "M",
    numStr: "2 689",
    numberValue: 2689,
    spanishText: "¿Cómo se dice 2 689 en español?",
    armenianText: "Ինչպե՞ս է 2 689-ը իսպաներեն։",
    wordInSpanish: "dos mil seiscientos ochenta y nueve",
    wrongOptions: ["dos mil setecientos ochenta y nueve", "dos mil seiscientos setenta y nueve", "dos mil seiscientos ochenta nueve"]
  },
  {
    id: 14,
    letter: "N",
    numStr: "3 754",
    numberValue: 3754,
    spanishText: "¿Cómo se dice 3 754 en español?",
    armenianText: "Ինչպե՞ս է 3 754-ը իսպաներեն։",
    wordInSpanish: "tres mil setecientos cincuenta y cuatro",
    wrongOptions: ["tres mil sietecientos cincuenta y cuatro", "tres mil setecientos cuarenta y cinco", "tres mil seiscientos cincuenta y cuatro"]
  },
  {
    id: 15,
    letter: "Ñ",
    numStr: "4 126",
    numberValue: 4126,
    spanishText: "¿Cómo se dice 4 126 en español?",
    armenianText: "Ինչպե՞ս է 4 126-ը իսպաներեն։",
    wordInSpanish: "cuatro mil ciento veintiséis",
    wrongOptions: ["cuatro mil cien veintiséis", "cuatro mil ciento veinte y seis", "cuatro mil doscientos veintiséis"]
  },
  {
    id: 16,
    letter: "O",
    numStr: "5 890",
    numberValue: 5890,
    spanishText: "¿Cómo se dice 5 890 en español?",
    armenianText: "Ինչպե՞ս է 5 890-ը իսպաներեն։",
    wordInSpanish: "cinco mil ochocientos noventa",
    wrongOptions: ["cinco mil ochocientos ochenta", "cinco mil ochocientos nueve", "cinco mil novecientos ochenta"]
  },
  {
    id: 17,
    letter: "P",
    numStr: "6 215",
    numberValue: 6215,
    spanishText: "¿Cómo se dice 6 215 en español?",
    armenianText: "Ինչպե՞ս է 6 215-ը իսպաներեն։",
    wordInSpanish: "seis mil doscientos quince",
    wrongOptions: ["seis mil doscientos cincuenta", "seis mil doscientos diez y cinco", "seis mil trescientos quince"]
  },
  {
    id: 18,
    letter: "Q",
    numStr: "7 804",
    numberValue: 7804,
    spanishText: "¿Cómo se dice 7 804 en español?",
    armenianText: "Ինչպե՞ս է 7 804-ը իսպաներեն։",
    wordInSpanish: "siete mil ochocientos cuatro",
    wrongOptions: ["siete mil ochocientos cuarenta", "siete mil ochocientos catorce", "siete mil setecientos cuatro"]
  },
  {
    id: 19,
    letter: "R",
    numStr: "8 670",
    numberValue: 8670,
    spanishText: "¿Cómo se dice 8 670 en español?",
    armenianText: "Ինչպե՞ս է 8 670-ը իսպաներեն։",
    wordInSpanish: "ocho mil seiscientos setenta",
    wrongOptions: ["ocho mil seiscientos sesenta", "ocho mil setecientos sesenta", "ocho mil seiscientos siete"]
  },
  {
    id: 20,
    letter: "S",
    numStr: "9 105",
    numberValue: 9105,
    spanishText: "¿Cómo se dice 9 105 en español?",
    armenianText: "Ինչպե՞ս է 9 105-ը իսպաներեն։",
    wordInSpanish: "nueve mil ciento cinco",
    wrongOptions: ["nueve mil cien cinco", "nueve mil ciento cincuenta", "nueve mil ciento quince"]
  },
  {
    id: 21,
    letter: "T",
    numStr: "735",
    numberValue: 735,
    spanishText: "¿Cómo se dice 735 en español?",
    armenianText: "Ինչպե՞ս է 735-ը իսպաներեն։",
    wordInSpanish: "setecientos treinta y cinco",
    wrongOptions: ["sietecientos treinta y cinco", "setecientos treinta cinco", "seiscientos treinta y cinco"]
  },
  {
    id: 22,
    letter: "U",
    numStr: "1 995",
    numberValue: 1995,
    spanishText: "¿Cómo se dice 1 995 en español?",
    armenianText: "Ինչպե՞ս է 1 995-ը իսպաներեն։",
    wordInSpanish: "mil novecientos noventa y cinco",
    wrongOptions: ["mil nuevecientos noventa y cinco", "un mil novecientos noventa y cinco", "mil novecientos ochenta y cinco"]
  },
  {
    id: 23,
    letter: "V",
    numStr: "2 340",
    numberValue: 2340,
    spanishText: "¿Cómo se dice 2 340 en español?",
    armenianText: "Ինչպե՞ս է 2 340-ը իսպաներեն։",
    wordInSpanish: "dos mil trescientos cuarenta",
    wrongOptions: ["dos mil trescientos cuatro", "dos mil trescientos catorce", "dos mil cuatrocientos treinta"]
  },
  {
    id: 24,
    letter: "W",
    numStr: "4 567",
    numberValue: 4567,
    spanishText: "¿Cómo se dice 4 567 en español?",
    armenianText: "Ինչպե՞ս է 4 567-ը իսպաներեն։",
    wordInSpanish: "cuatro mil quinientos sesenta y siete",
    wrongOptions: ["cuatro mil cincocientos sesenta y siete", "cuatro mil quinientos setenta y seis", "cuatro mil quinientos sesenta siete"]
  },
  {
    id: 25,
    letter: "X",
    numStr: "6 789",
    numberValue: 6789,
    spanishText: "¿Cómo se dice 6 789 en español?",
    armenianText: "Ինչպե՞ս է 6 789-ը իսպաներեն։",
    wordInSpanish: "seis mil setecientos ochenta y nueve",
    wrongOptions: ["seis mil sietecientos ochenta y nueve", "seis mil setecientos noventa y ocho", "seis mil ochocientos setenta y nueve"]
  },
  {
    id: 26,
    letter: "Y",
    numStr: "12 200",
    numberValue: 12200,
    spanishText: "¿Cómo se dice 12 200 en español?",
    armenianText: "Ինչպե՞ս է 12 200-ը իսպաներեն։",
    wordInSpanish: "doce mil doscientos",
    wrongOptions: ["diez y dos mil doscientos", "doce mil cien", "veinte mil doscientos"]
  },
  {
    id: 27,
    letter: "Z",
    numStr: "9 999",
    numberValue: 9999,
    spanishText: "¿Cómo se dice 9 999 en español?",
    armenianText: "Ինչպե՞ս է 9 999-ը իսպաներեն։",
    wordInSpanish: "nueve mil novecientos noventa y nueve",
    wrongOptions: ["nueve mil nuevecientos noventa y nueve", "diez mil novecientos noventa y nueve", "nueve mil novecientos noventa"]
  },
];

// 4. PROBLEMAS MATEMÁTICOS: 15 problemas
export const PROBLEMAS_MATEMATICOS: MathProblem[] = [
  {
    id: 1,
    spanish: "Ana tiene 320 euros y recibe 180 euros más. ¿Cuánto dinero tiene ahora?",
    armenian: "Անան ունի 320 եվրո և ստանում է ևս 180 եվրո։ Հիմա որքա՞ն գումար ունի։",
    result: 500,
    unitEs: "euros",
    unitHy: "եվրո",
    operation: "320 + 180 = 500",
    explanationEs: "Sumamos la cantidad inicial más lo que recibe: 320 € + 180 € = 500 € (quinientos euros).",
    explanationHy: "Գումարում ենք սկզբնական գումարին ստացածը՝ 320 + 180 = 500 եվրո։",
  },
  {
    id: 2,
    spanish: "En una tienda hay 1 250 botellas. Venden 430. ¿Cuántas quedan?",
    armenian: "Խանութում կա 1 250 շիշ։ Վաճառում են 430-ը։ Քանի՞ շիշ է մնում։",
    result: 820,
    unitEs: "botellas",
    unitHy: "շիշ",
    operation: "1250 - 430 = 820",
    explanationEs: "Restamos las botellas vendidas de las iniciales: 1 250 - 430 = 820 botellas (ochocientas veinte botellas).",
    explanationHy: "Հանում ենք վաճառված շշերը՝ 1 250 - 430 = 820 շիշ։",
  },
  {
    id: 3,
    spanish: "Carlos compra 6 cajas con 24 botellas en cada una. ¿Cuántas botellas compra en total?",
    armenian: "Կառլոսը գնում է 6 տուփ, յուրաքանչյուրում՝ 24 շիշ։ Ընդհանուր քանի՞ շիշ է գնում։",
    result: 144,
    unitEs: "botellas",
    unitHy: "շիշ",
    operation: "6 × 24 = 144",
    explanationEs: "Multiplicamos el número de cajas por las botellas en cada una: 6 × 24 = 144 (ciento cuarenta y cuatro botellas).",
    explanationHy: "Բազմապատկում ենք տուփերի քանակը մեկ տուփի շշերի քանակով՝ 6 × 24 = 144 շիշ։",
  },
  {
    id: 4,
    spanish: "Un autobús lleva 48 pasajeros. En una parada bajan 17 y suben 9. ¿Cuántos pasajeros hay ahora?",
    armenian: "Ավտոբուսում կա 48 ուղևոր։ Կանգառում 17-ը իջնում են, 9-ը՝ բարձրանում։ Հիմա քանի՞ ուղևոր կա։",
    result: 40,
    unitEs: "pasajeros",
    unitHy: "ուղևոր",
    operation: "48 - 17 + 9 = 40",
    explanationEs: "Restamos los que bajan y sumamos los que suben: 48 - 17 = 31; 31 + 9 = 40 pasajeros (cuarenta pasajeros).",
    explanationHy: "Հանում ենք իջնողներին և գումարում բարձրացողներին՝ 48 - 17 + 9 = 40 ուղևոր։",
  },
  {
    id: 5,
    spanish: "María tiene 2 400 euros. Gasta 875 euros. ¿Cuánto dinero le queda?",
    armenian: "Մարիան ունի 2 400 եվրո։ Նա ծախսում է 875 եվրո։ Որքա՞ն գումար է մնում։",
    result: 1525,
    unitEs: "euros",
    unitHy: "եվրո",
    operation: "2400 - 875 = 1525",
    explanationEs: "Restamos el gasto del total: 2 400 - 875 = 1 525 € (mil quinientos veinticinco euros).",
    explanationHy: "Հանում ենք ծախսած գումարը՝ 2 400 - 875 = 1 525 եվրո։",
  },
  {
    id: 6,
    spanish: "Hay 360 libros y se reparten entre 6 clases. ¿Cuántos libros recibe cada clase?",
    armenian: "Կա 360 գիրք, և դրանք բաժանում են 6 դասարանի միջև։ Յուրաքանչյուր դասարան քանի՞ գիրք է ստանում։",
    result: 60,
    unitEs: "libros",
    unitHy: "գիրք",
    operation: "360 ÷ 6 = 60",
    explanationEs: "Dividimos la cantidad total de libros entre las 6 clases: 360 ÷ 6 = 60 libros (sesenta libros).",
    explanationHy: "Բաժանում ենք 360-ը 6-ի՝ 360 ÷ 6 = 60 գիրք։",
  },
  {
    id: 7,
    spanish: "Pedro compra 3 entradas de 28 euros cada una. ¿Cuánto paga en total?",
    armenian: "Պեդրոն գնում է 3 տոմս՝ յուրաքանչյուրը 28 եվրո։ Ընդհանուր որքա՞ն է վճարում։",
    result: 84,
    unitEs: "euros",
    unitHy: "եվրո",
    operation: "3 × 28 = 84",
    explanationEs: "Multiplicamos 3 entradas por 28 € cada una: 3 × 28 = 84 € (ochenta y cuatro euros).",
    explanationHy: "Բազմապատկում ենք տոմսերի քանակը գնով՝ 3 × 28 = 84 եվրո։",
  },
  {
    id: 8,
    spanish: "En un almacén hay 5 600 cajas. Llegan 1 250 cajas más. ¿Cuántas hay ahora?",
    armenian: "Պահեստում կա 5 600 տուփ։ Բերում են ևս 1 250 տուփ։ Հիմա քանի՞ տուփ կա։",
    result: 6850,
    unitEs: "cajas",
    unitHy: "տուփ",
    operation: "5600 + 1250 = 6850",
    explanationEs: "Sumamos las cajas recibidas: 5 600 + 1 250 = 6 850 cajas (seis mil ochocientas cincuenta cajas).",
    explanationHy: "Գումարում ենք բերված տուփերը՝ 5 600 + 1 250 = 6 850 տուփ։",
  },
  {
    id: 9,
    spanish: "Lucía tiene 950 euros y quiere comprar un teléfono que cuesta 1 200 euros. ¿Cuánto dinero le falta?",
    armenian: "Լուսիան ունի 950 եվրո և ուզում է գնել 1 200 եվրո արժողությամբ հեռախոս։ Որքա՞ն գումար է նրան պակասում։",
    result: 250,
    unitEs: "euros",
    unitHy: "եվրո",
    operation: "1200 - 950 = 250",
    explanationEs: "Restamos lo que tiene del precio del teléfono: 1 200 - 950 = 250 € (doscientos cincuenta euros).",
    explanationHy: "Հեռախոսի արժեքից հանում ենք եղած գումարը՝ 1 200 - 950 = 250 եվրո։",
  },
  {
    id: 10,
    spanish: "Un tren recorre 180 kilómetros por la mañana y 245 por la tarde. ¿Cuántos kilómetros recorre en total?",
    armenian: "Գնացքը առավոտյան անցնում է 180 կմ, իսկ կեսօրից հետո՝ 245 կմ։ Ընդհանուր քանի՞ կմ է անցնում։",
    result: 425,
    unitEs: "kilómetros",
    unitHy: "կմ",
    operation: "180 + 245 = 425",
    explanationEs: "Sumamos ambas distancias: 180 + 245 = 425 km (cuatrocientos veinticinco kilómetros).",
    explanationHy: "Գումարում ենք առավոտյան և կեսօրվա անցած ճանապարհները՝ 180 + 245 = 425 կմ։",
  },
  {
    id: 11,
    spanish: "Hay 2 700 naranjas. Se colocan en cajas de 30. ¿Cuántas cajas se necesitan?",
    armenian: "Կա 2 700 նարինջ։ Դրանք դնում են 30-ական նարինջ ունեցող տուփերի մեջ։ Քանի՞ տուփ է անհրաժեշտ։",
    result: 90,
    unitEs: "cajas",
    unitHy: "տուփ",
    operation: "2700 ÷ 30 = 90",
    explanationEs: "Dividimos el total de naranjas entre la capacidad de cada caja: 2 700 ÷ 30 = 90 cajas (noventa cajas).",
    explanationHy: "Նարինջների ընդհանուր քանակը բաժանում ենք 30-ի՝ 2 700 ÷ 30 = 90 տուփ։",
  },
  {
    id: 12,
    spanish: "José compra una chaqueta por 85 euros y unos zapatos por 120 euros. ¿Cuánto paga?",
    armenian: "Խոսեն գնում է բաճկոն՝ 85 եվրոյով, և կոշիկ՝ 120 եվրոյով։ Ընդհանուր որքա՞ն է վճարում։",
    result: 205,
    unitEs: "euros",
    unitHy: "եվրո",
    operation: "85 + 120 = 205",
    explanationEs: "Sumamos el valor de la chaqueta y los zapatos: 85 € + 120 € = 205 € (doscientos cinco euros).",
    explanationHy: "Գումարում ենք բաճկոնի և կոշիկների արժեքը՝ 85 + 120 = 205 եվրո։",
  },
  {
    id: 13,
    spanish: "Una familia tiene 3 500 euros. Paga 1 200 euros de alquiler y 650 euros de otros gastos. ¿Cuánto dinero queda?",
    armenian: "Ընտանիքն ունի 3 500 եվրո։ Վճարում է 1 200 եվրո վարձ և 650 եվրո այլ ծախսերի համար։ Որքա՞ն գումար է մնում։",
    result: 1650,
    unitEs: "euros",
    unitHy: "եվրո",
    operation: "3500 - 1200 - 650 = 1650",
    explanationEs: "Total de gastos: 1 200 + 650 = 1 850 €. Queda: 3 500 - 1 850 = 1 650 € (mil seiscientos cincuenta euros).",
    explanationHy: "Ծախսերի ընդհանուր գումարը՝ 1 850 եվրո։ Մնում է՝ 3 500 - 1 850 = 1 650 եվրո։",
  },
  {
    id: 14,
    spanish: "Una escuela tiene 8 clases con 27 alumnos en cada clase. ¿Cuántos alumnos hay en total?",
    armenian: "Դպրոցում կա 8 դասարան, յուրաքանչյուրում՝ 27 աշակերտ։ Ընդհանուր քանի՞ աշակերտ կա։",
    result: 216,
    unitEs: "alumnos",
    unitHy: "աշակերտ",
    operation: "8 × 27 = 216",
    explanationEs: "Multiplicamos el número de clases por los alumnos de cada una: 8 × 27 = 216 alumnos (doscientos dieciséis alumnos).",
    explanationHy: "Դասարանների քանակը բազմապատկում ենք աշակերտների թվով՝ 8 × 27 = 216 աշակերտ։",
  },
  {
    id: 15,
    spanish: "En un supermercado reciben 4 800 productos y venden 2 350. ¿Cuántos productos quedan?",
    armenian: "Սուպերմարկետը ստանում է 4 800 ապրանք և վաճառում 2 350-ը։ Քանի՞ ապրանք է մնում։",
    result: 2450,
    unitEs: "productos",
    unitHy: "ապրանք",
    operation: "4800 - 2350 = 2450",
    explanationEs: "Restamos los productos vendidos: 4 800 - 2 350 = 2 450 productos (dos mil cuatrocientos cincuenta productos).",
    explanationHy: "Հանում ենք վաճառված ապրանքները՝ 4 800 - 2 350 = 2 450 ապրանք։",
  },
];
